
//////////////////////////////////////////////////////////////////////
// This is a driver ViewKit program generated by RapidApp 1.1 

//
// This program instantiates a ViewKit VkApp object and creates
// any main window objects that are meant to be shown at startup.
// There should rarely be a reason to modify this file.
// Make application-specific changes in the classes created
// by the main window classes
// Some applications may wish to change this code to instantiate
// a different application class, however.
//////////////////////////////////////////////////////////////////////
#include <Vk/VkApp.h>


// Headers for classes used in this program

#include "VkwindowMainWindow.h"

//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


void main ( int argc, char **argv )
{
    extern void InitEZ(void);

    InitEZ();
    //---- Start editable code block: main initialization

    //---- End editable code block: main initialization

    VkApp       *app;

    // Create an application object
    app = new VkApp("Application", &argc, argv); 

    // Create the top level windows

    VkSimpleWindow *vkwindow  = new VkwindowMainWindow("vkwindow");
    vkwindow->show();

    //---- Start editable code block:  event loop

    //---- End editable code block:  event loop
    app->run ();
}
//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

