
//////////////////////////////////////////////////////////////
//
// Header file for MenuBar1
//
//    This file is generated by RapidApp 1.1
//
//    This class is derived from MenuBar1UI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this header file, limit your changes to
//    those areas between the "//--- Start/End editable code block" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//////////////////////////////////////////////////////////////
#ifndef MENUBAR1_H
#define MENUBAR1_H
#include "MenuBar1UI.h"

#include <Vk/VkSimpleWindow.h>
//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


//---- MenuBar1 class declaration

class MenuBar1 : public MenuBar1UI
{

  public:

    MenuBar1(const char *, Widget);
    MenuBar1(const char *);
    ~MenuBar1();
    const char *  className();

    //---- Start editable code block: MenuBar1 public


    //---- End editable code block: MenuBar1 public



  protected:

    //---- Start editable code block: MenuBar1 protected


    //---- End editable code block: MenuBar1 protected



  private:

    //---- Start editable code block: MenuBar1 private


    //---- End editable code block: MenuBar1 private


};
#endif

