
/////////////////////////////////////////////////////////////
//
// Source file for BulletinBoard
//
//    This file is generated by RapidApp 1.1
//
//    This class is derived from BulletinBoardUI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this source, limit your changes to 
//    modifying the sections between the "//--- Start/End editable code block" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
/////////////////////////////////////////////////////////////

#include "BulletinBoard.h"
#include <Vk/VkEZ.h>
#include <Xm/BulletinB.h> 
#include <Xm/Label.h> 
#include <Xm/Separator.h> 
#include <Xm/TextF.h> 
#include <Vk/VkResource.h>
#include <Vk/VkWindow.h>
#include <Vk/VkMenuBar.h>
#include <Vk/VkSubMenu.h>

extern void VkUnimplemented(Widget, const char *);

///////////////////////////////////////////////////////////////////////////////
// The following non-container widgets are created by BulletinBoardUI and are
// available as protected data members inherited by this class
//
//  XmLabel		    _torusSizeLabel
//  XmLabel		    _label8
//  XmLabel		    _winSizeLabel
//  XmLabel		    _label6
//  XmLabel		    _estWorkLabel
//  XmLabel		    _label4
//  XmSeparator		    _separator3
//  XmLabel		    _label3
//  XmSeparator		    _separator2
//  XmTextField		    _omegaSize
//  XmLabel		    _label2
//  XmTextField		    _omegaYPos
//  XmLabel		    _label1
//  XmTextField		    _omegaXPos
//  XmLabel		    _label
//
///////////////////////////////////////////////////////////////////////////////


//---- Start editable code block: headers and declarations

#include	<stdio.h>

//---- End editable code block: headers and declarations



//---- BulletinBoard Constructor

BulletinBoard::BulletinBoard(const char *name, Widget parent) : 
                   BulletinBoardUI(name, parent) 
{ 
    // This constructor calls BulletinBoardUI(parent, name)
    // which calls BulletinBoardUI::create() to create
    // the widgets for this component. Any code added here
    // is called after the component's interface has been built

    //---- Start editable code block: BulletinBoard constructor


    //---- End editable code block: BulletinBoard constructor



} // End Constructor



BulletinBoard::BulletinBoard(const char *name) : 
                   BulletinBoardUI(name) 
 { 
    // This constructor calls BulletinBoardUI(name)
    // which does not create any widgets. Usually, this
    // constructor is not used

    //---- Start editable code block: BulletinBoard constructor 2


    //---- End editable code block: BulletinBoard constructor 2



} // End Constructor



BulletinBoard::~BulletinBoard()
{
    // The base class destructors are responsible for
    // destroying all widgets and objects used in this component.
    // Only additional items created directly in this class
    // need to be freed here.

    //---- Start editable code block: BulletinBoard destructor


    //---- End editable code block: BulletinBoard destructor



}


const char * BulletinBoard::className() // classname
{
    return ("BulletinBoard");
} // End className()


void BulletinBoard::setOmegaXPos ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setOmegaXPos

    XmTextVerifyCallbackStruct *cbs = (XmTextVerifyCallbackStruct*) callData;

    char *str = XmTextFieldGetString( w );

    printf( "BulletinBoard::setOmegaXPos = %s\n", str );

    //---- End editable code block: BulletinBoard setOmegaXPos

} // End BulletinBoard::setOmegaXPos()


void BulletinBoard::setNumSamples1 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples1

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples1 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples1" );




    //---- End editable code block: BulletinBoard setNumSamples1

} // End BulletinBoard::setNumSamples1()


void BulletinBoard::setNumSamples128 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples128

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples128 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples128" );




    //---- End editable code block: BulletinBoard setNumSamples128

} // End BulletinBoard::setNumSamples128()


void BulletinBoard::setNumSamples16 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples16

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples16 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples16" );




    //---- End editable code block: BulletinBoard setNumSamples16

} // End BulletinBoard::setNumSamples16()


void BulletinBoard::setNumSamples2 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples2

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples2 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples2" );




    //---- End editable code block: BulletinBoard setNumSamples2

} // End BulletinBoard::setNumSamples2()


void BulletinBoard::setNumSamples256 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples256

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples256 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples256" );




    //---- End editable code block: BulletinBoard setNumSamples256

} // End BulletinBoard::setNumSamples256()


void BulletinBoard::setNumSamples32 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples32

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples32 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples32" );




    //---- End editable code block: BulletinBoard setNumSamples32

} // End BulletinBoard::setNumSamples32()


void BulletinBoard::setNumSamples4 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples4

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples4 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples4" );




    //---- End editable code block: BulletinBoard setNumSamples4

} // End BulletinBoard::setNumSamples4()


void BulletinBoard::setNumSamples64 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples64

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples64 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples64" );




    //---- End editable code block: BulletinBoard setNumSamples64

} // End BulletinBoard::setNumSamples64()


void BulletinBoard::setNumSamples8 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumSamples8

    XmAnyCallbackStruct *cbs = (XmAnyCallbackStruct*) callData;

    //--- Comment out the following line when BulletinBoard::setNumSamples8 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumSamples8" );




    //---- End editable code block: BulletinBoard setNumSamples8

} // End BulletinBoard::setNumSamples8()


void BulletinBoard::setNumTorus1 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus1

    setNumTorusTiles( 1 );

    //---- End editable code block: BulletinBoard setNumTorus1

} // End BulletinBoard::setNumTorus1()


void BulletinBoard::setNumTorus128 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus128

    setNumTorusTiles( 128 );

    //--- Comment out the following line when BulletinBoard::setNumTorus128 is implemented:

    ::VkUnimplemented ( w, "BulletinBoard::setNumTorus128" );




    //---- End editable code block: BulletinBoard setNumTorus128

} // End BulletinBoard::setNumTorus128()


void BulletinBoard::setNumTorus16 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus16

    setNumTorusTiles( 16 );

    //---- End editable code block: BulletinBoard setNumTorus16

} // End BulletinBoard::setNumTorus16()


void BulletinBoard::setNumTorus2 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus2

    setNumTorusTiles( 2 );

    //---- End editable code block: BulletinBoard setNumTorus2

} // End BulletinBoard::setNumTorus2()


void BulletinBoard::setNumTorus256 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus256

    setNumTorusTiles( 256 );

    //---- End editable code block: BulletinBoard setNumTorus256

} // End BulletinBoard::setNumTorus256()


void BulletinBoard::setNumTorus32 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus32

    setNumTorusTiles( 32 );

    //---- End editable code block: BulletinBoard setNumTorus32

} // End BulletinBoard::setNumTorus32()


void BulletinBoard::setNumTorus4 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus4

    setNumTorusTiles( 4 );

    //---- End editable code block: BulletinBoard setNumTorus4

} // End BulletinBoard::setNumTorus4()


void BulletinBoard::setNumTorus64 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus64

    setNumTorusTiles( 64 );

    //---- End editable code block: BulletinBoard setNumTorus64

} // End BulletinBoard::setNumTorus64()


void BulletinBoard::setNumTorus8 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setNumTorus8

    setNumTorusTiles( 8 );

    //---- End editable code block: BulletinBoard setNumTorus8

} // End BulletinBoard::setNumTorus8()


void BulletinBoard::setOmegaWindowSize ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setOmegaWindowSize

    char *str = XmTextFieldGetString( w );

    printf( "BulletinBoard::setOmegaWindowSize = %s\n", str );




    //---- End editable code block: BulletinBoard setOmegaWindowSize

} // End BulletinBoard::setOmegaWindowSize()



void BulletinBoard::setOmegaYPos ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setOmegaYPos

    char *str = XmTextFieldGetString( w );

    printf( "BulletinBoard::setOmegaYPos = %s\n", str );

    //---- End editable code block: BulletinBoard setOmegaYPos

} // End BulletinBoard::setOmegaYPos()


void BulletinBoard::setSampleSize1 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize1

    setSampleTileSize( 1 );

    //---- End editable code block: BulletinBoard setSampleSize1

} // End BulletinBoard::setSampleSize1()


void BulletinBoard::setSampleSize128 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize128

    setSampleTileSize( 128 );

    //---- End editable code block: BulletinBoard setSampleSize128

} // End BulletinBoard::setSampleSize128()


void BulletinBoard::setSampleSize16 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize16

    setSampleTileSize( 16 );

    //---- End editable code block: BulletinBoard setSampleSize16

} // End BulletinBoard::setSampleSize16()


void BulletinBoard::setSampleSize2 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize2

    setSampleTileSize( 2 );



    //---- End editable code block: BulletinBoard setSampleSize2

} // End BulletinBoard::setSampleSize2()


void BulletinBoard::setSampleSize256 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize256

    setSampleTileSize( 256 );

    //---- End editable code block: BulletinBoard setSampleSize256

} // End BulletinBoard::setSampleSize256()


void BulletinBoard::setSampleSize32 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize32

    setSampleTileSize( 32 );

    //---- End editable code block: BulletinBoard setSampleSize32

} // End BulletinBoard::setSampleSize32()


void BulletinBoard::setSampleSize4 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize4

    setSampleTileSize( 4 );

    //---- End editable code block: BulletinBoard setSampleSize4

} // End BulletinBoard::setSampleSize4()


void BulletinBoard::setSampleSize64 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize64

    setSampleTileSize( 64 );

    //---- End editable code block: BulletinBoard setSampleSize64

} // End BulletinBoard::setSampleSize64()


void BulletinBoard::setSampleSize8 ( Widget w, XtPointer callData )
{
    //---- Start editable code block: BulletinBoard setSampleSize8

    setSampleTileSize( 8 );




    //---- End editable code block: BulletinBoard setSampleSize8

} // End BulletinBoard::setSampleSize8()


void BulletinBoard::setParent( VkWindow  * parent )
{
    // Store a pointer to the parent VkWindow. This can
    // be useful for accessing the menubar from this class.


    _parent = parent;

} // End BulletinBoard::setParent()





///////////////////////////////////////////////////////////////////
// C-callable creation function, for importing class into rapidapp
///////////////////////////////////////////////////////////////////


extern "C" VkComponent * CreateBulletinBoard( const char *name, Widget parent ) 
{  
    VkComponent *obj =  new BulletinBoard ( name, parent );
    obj->show();

    return ( obj );
} // End CreateBulletinBoard


///////////////////////////////////////////////////////////////////
// Function for importing this class into rapidapp
// This function is only used by RapidApp.
///////////////////////////////////////////////////////////////////


typedef void (BulletinBoard::*Method) (void);
struct FunctionMap {
  char  *resource;  Method method;  char  *code;
  char  *type;
};


extern "C" void* RegisterBulletinBoardInterface()
{ 
    // This structure registers information about this class
    // that allows RapidApp to create and manipulate an instance.
    // Each entry provides a resource name that will appear in the
    // resource manager palette when an instance of this class is
    // selected, the relative address of the member function that
    // should be invoked when the resource is set, the name of the
    // member function as a string, and the type of the single 
    // argument to this function. All functions must have the form
    //  
    //  void memberFunction(Type);
    //
    // where "Type" is one of const char *, Boolean, or int. Use
    // XmRString, XmRBoolean, or XmRInt to describe the argument type


    static FunctionMap map[] = {
    //---- Start editable code block: BulletinBoardUI resource table

      // { "resourceName", (Method) &BulletinBoard::setAttribute, "setAttribute", XmRString},
    //---- End editable code block: BulletinBoardUI resource table
      { NULL }, // MUST be NULL terminated
    };

    return map;
} // End RegisterBulletinBoardInterface()






//---- End of generated code

//---- Start editable code block: End of generated code

void
BulletinBoard::config()
{
    int work = numSamples * sampleTileSize;
    work *= work;

    int windowSize = numSamples*sampleTileSize;

    int torusSize = windowSize*numTorusTiles;

    char	str[32];

    sprintf( str, "%d", work );		EZ(_estWorkLabel) = str;
    sprintf( str, "%d", windowSize );	EZ(_winSizeLabel) = str;
    sprintf( str, "%d", torusSize );	EZ(_torusSizeLabel) = str;
}


void
BulletinBoard::setNumTorusTiles( int num )
{
    numTorusTiles = num;
    config();
}


void
BulletinBoard::setSampleTileSize( int s )
{
    sampleTileSize = s;
    config();
}



//---- End editable code block: End of generated code



