
/////////////////////////////////////////////////////////////
//
// Source file for MenuBar1
//
//    This file is generated by RapidApp 1.1
//
//    This class is derived from MenuBar1UI which 
//    implements the user interface created in 
//    the interface builder. This class contains virtual
//    functions that are called from the user interface.
//
//    When you modify this source, limit your changes to 
//    modifying the sections between the "//--- Start/End editable code block" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
/////////////////////////////////////////////////////////////

#include "MenuBar1.h"
#include <Vk/VkEZ.h>
#include <Vk/VkResource.h>
#include <Vk/VkSimpleWindow.h>

extern void VkUnimplemented(Widget, const char *);

///////////////////////////////////////////////////////////////////////////////
// The following non-container widgets are created by MenuBar1UI and are
// available as protected data members inherited by this class
//
//  XmPushButtonGadget		    _action1
//  XmPushButtonGadget		    _action2
//  XmPushButtonGadget		    _action3
//  XmPushButtonGadget		    _action4
//  XmPushButtonGadget		    _action5
//  XmPushButtonGadget		    _action6
//
///////////////////////////////////////////////////////////////////////////////


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations



//---- MenuBar1 Constructor

MenuBar1::MenuBar1(const char *name, Widget parent) : 
                   MenuBar1UI(name, parent) 
{ 
    // This constructor calls MenuBar1UI(parent, name)
    // which calls MenuBar1UI::create() to create
    // the widgets for this component. Any code added here
    // is called after the component's interface has been built

    //---- Start editable code block: MenuBar1 constructor


    //---- End editable code block: MenuBar1 constructor



} // End Constructor



MenuBar1::MenuBar1(const char *name) : 
                   MenuBar1UI(name) 
 { 
    // This constructor calls MenuBar1UI(name)
    // which does not create any widgets. Usually, this
    // constructor is not used

    //---- Start editable code block: MenuBar1 constructor 2


    //---- End editable code block: MenuBar1 constructor 2



} // End Constructor



MenuBar1::~MenuBar1()
{
    // The base class destructors are responsible for
    // destroying all widgets and objects used in this component.
    // Only additional items created directly in this class
    // need to be freed here.

    //---- Start editable code block: MenuBar1 destructor


    //---- End editable code block: MenuBar1 destructor



}


const char * MenuBar1::className() // classname
{
    return ("MenuBar1");
} // End className()





///////////////////////////////////////////////////////////////////
// C-callable creation function, for importing class into rapidapp
///////////////////////////////////////////////////////////////////


extern "C" VkComponent * CreateMenuBar1( const char *name, Widget parent ) 
{  
    VkComponent *obj =  new MenuBar1 ( name, parent );
    obj->show();

    return ( obj );
} // End CreateMenuBar1


///////////////////////////////////////////////////////////////////
// Function for importing this class into rapidapp
// This function is only used by RapidApp.
///////////////////////////////////////////////////////////////////


typedef void (MenuBar1::*Method) (void);
struct FunctionMap {
  char  *resource;  Method method;  char  *code;
  char  *type;
};


extern "C" void* RegisterMenuBar1Interface()
{ 
    // This structure registers information about this class
    // that allows RapidApp to create and manipulate an instance.
    // Each entry provides a resource name that will appear in the
    // resource manager palette when an instance of this class is
    // selected, the relative address of the member function that
    // should be invoked when the resource is set, the name of the
    // member function as a string, and the type of the single 
    // argument to this function. All functions must have the form
    //  
    //  void memberFunction(Type);
    //
    // where "Type" is one of const char *, Boolean, or int. Use
    // XmRString, XmRBoolean, or XmRInt to describe the argument type


    static FunctionMap map[] = {
    //---- Start editable code block: MenuBar1UI resource table

      // { "resourceName", (Method) &MenuBar1::setAttribute, "setAttribute", XmRString},
    //---- End editable code block: MenuBar1UI resource table
      { NULL }, // MUST be NULL terminated
    };

    return map;
} // End RegisterMenuBar1Interface()






//---- End of generated code

//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code


