
//////////////////////////////////////////////////////////////
//
// Header file for MenuBar1UI
//
//    This file is generated by RapidApp 1.1
//
//    This class implements the user interface portion of a class
//    the interface builder. Normally it is not used directly.
//    Instead the subclass, MenuBar1 is instantiated
//
//    To extend or alter the behavior of this class, you should
//    modify the MenuBar1 files
//
//    Restrict changes to those sections between
//    the "//--- Start/End editable code block" markers
//
//    This will allow the builder to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef MENUBAR1UI_H
#define MENUBAR1UI_H
#include <Vk/VkComponent.h>


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


class MenuBar1UI : public VkComponent
{ 

  public:

    MenuBar1UI(const char *, Widget);
    MenuBar1UI(const char *);
    ~MenuBar1UI();
    void create ( Widget );
    const char *  className();

    //---- Start editable code block: MenuBar1 public


    //---- End editable code block: MenuBar1 public


  protected:


    // Widgets created by this class





    //---- Start editable code block: MenuBar1 protected


    //---- End editable code block: MenuBar1 protected


  private: 
    // Array of default resources

    static String      _defaultMenuBar1UIResources[];
    //---- Start editable code block: MenuBar1 private


    //---- End editable code block: MenuBar1 private
};
#endif

